from datetime import timedelta
from decouple import config

ACCESS_TOKEN_LIFETIME_IN_MINUTES = config('ACCESS_TOKEN_LIFETIME_IN_MINUTES', 10)
REFRESH_TOKEN_LIFETIME_IN_DAYS = config('REFRESH_TOKEN_LIFETIME_IN_DAYS', 180)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(ACCESS_TOKEN_LIFETIME_IN_MINUTES)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(REFRESH_TOKEN_LIFETIME_IN_DAYS)),

    'AUTH_HEADER_TYPES': ('JWT',),

}
